export const dummySongs = [
  {
    rank: 1,
    title: 'Like a Rolling Stone',
    artist: 'Bob Dylan',
    album: 'Highway 61 Revisited',
    year: '1965',
  },
  {
    rank: 2,
    title: "(I Can't Get No) Satisfaction",
    artist: 'The Rolling Stones',
    album: 'Out of Our Heads',
    year: '1965',
  },
  {
    rank: 3,
    title: 'Imagine',
    artist: 'John Lennon',
    album: 'Imagine',
    year: '1971',
  },
  {
    rank: 4,
    title: "What's Going On",
    artist: 'Marvin Gaye',
    album: "What's Going On",
    year: '1971',
  },
  {
    rank: 5,
    title: 'Respect',
    artist: 'Aretha Franklin',
    album: 'I Never Loved a Man the Way I Love You',
    year: '1967',
  },
  {
    rank: 6,
    title: 'Good Vibrations',
    artist: 'The Beach Boys',
    album: 'Smiley Smile/Wild Honey',
    year: '1966',
  },
  {
    rank: 7,
    title: 'Johnny B. Goode',
    artist: 'Chuck Berry',
    album: 'The Anthology',
    year: '1958',
  },
  {
    rank: 8,
    title: 'Hey Jude',
    artist: 'The Beatles',
    album: 'Hey Jude',
    year: '1968',
  },
  {
    rank: 9,
    title: 'Smells Like Teen Spirit',
    artist: 'Nirvana',
    album: 'Nevermind',
    year: '1991',
  },
  {
    rank: 10,
    title: "What'd I Say",
    artist: 'Ray Charles',
    album: "What'd I Say",
    year: '1959',
  },
  {
    rank: 11,
    title: 'My Generation',
    artist: 'The Who',
    album: 'My Generation',
    year: '1965',
  },
  {
    rank: 12,
    title: 'A Change Is Gonna Come',
    artist: 'Sam Cooke',
    album: 'Portrait of a Legend 1951-1964',
    year: '1964',
  },
  {
    rank: 13,
    title: 'Yesterday',
    artist: 'The Beatles',
    album: 'Help!',
    year: '1965',
  },
  {
    rank: 14,
    title: "Blowin' in the Wind",
    artist: 'Bob Dylan',
    album: "The Freewheelin' Bob Dylan",
    year: '1963',
  },
  {
    rank: 15,
    title: 'London Calling',
    artist: 'The Clash',
    album: 'London Calling',
    year: '1980',
  },
]
